### PR TITLE
Velocity fix

### LINKED ISSUE #35: Delta Ejection Velocity != Velocity
## Ejection velocity saved as Velocity (aka Ignoring starting velocity)
The model "Satellite" currently does only contain a member velocity. This is NOT sufficient!
The simulation does save the ejection velocity for each satellite but ignores the starting velocities of the exploding/ colliding satellite(s). I noticed the error by the production of ground tracks that every fragment had an unreasonably high eccentricity from nearly circular parent objects.

- [x] Differentiate between Ejection Velocity and Velocity and use the later for the Keplerian Elements
- [x] Implement the assignment which debris originates from which parent object according to the python implementation

### PR DESCRIPTION
**Pull request by schuhmaj**
# (Ejection) Velocity Correction Fix
## The problem
This PR solves the issue that the current simulation does save and output only the ejection velocity (Delta V Distribution in the Paper) as the satellites' velocities. This not directly a problem but is odd if one wants to continue calculating orbits. (resolves #35)

I noticed this behaviour by plotting the orbits of the output fragments which all where highly eccentric which seemed unreasonable (after finally understanding how to parse the csv to float numpy arrays).

## The Fix

- Each satellite now has two separated velocities:
  - **The ejection velocity** produced by the simulation (This was saved as velocity before)
  - **The velocity** as the sum of the ejection velocity and the parent body's velocity
- So as hinted before now every debris fragment has a unique parent
  - **Explosion Case:** Trivial because we only have one parent
  - **Collision Case:** I've implemented the procedure from the Python Implementation. This includes the following logic:
    - If the fragment is greater than the smaller parent satellite it has to origin from the bigger parent satellite
    - The distribution of L_c values is random, so I assign every satellite which has not been covered by the previous step the origin bigger parent until "the available mass-budget" (see below) is consumed, then the rest fragments are assigned the origin smaller parent satellite.
- Furthermore, the simulation now checks if the produced debris' mass exceeds the input mass and if so throws away the overhang

**Available mass budget Calculation:**
The mass of debris which originates from the bigger satellites must be smaller than.
(Mass Big Parent Satellite) * (Total Mass Simulation/ Total Mass Input)
In other word the mass of the big parent satellite is normed to the actual produced mass by the simulation.

## Comparison of the Approach
Compare
https://github.com/richardklima/Space_debris_removal_model/blob/master/breakup.py
lines 244 - 266

## Note
This PR does already contain the fix for the TLE Reader

### CODE REVIEW

File: src/breakupModel/simulation/Collision.cpp [hunk 1]
```diff
@@ -39,17 +39,59 @@ void Collision::generateFragments() {
...
+            sat.setVelocity(bigSat.getVelocity());
+            assignedBigMass += sat.getMass();
+        }
+    }
+
+    //Assign the rest with respect to the already assigned debris-mass for the big satellite
+    //first if: the mass of the bigSat is normed to the actual produced mass of the simulation
+    for (auto &sat : _output) {
+        if (sat.getCharacteristicLength() <= smallSat.getCharacteristicLength()
+            && assignedBigMass < bigSat.getMass() * resultMass / inputMass) {
```
Comment (gomezzz) [inline src/breakupModel/simulation/Collision.cpp:84]: it seems like you recompute `bigSat.getMass() * resultMass / inputMass` a lot of times here

File: src/breakupModel/simulation/Collision.cpp [hunk 2]
```diff
@@ -39,17 +39,59 @@ void Collision::generateFragments() {
...
+        if (sat.getCharacteristicLength() > smallSat.getCharacteristicLength()) {
+            sat.setName(debrisNameBigPtr);
+            sat.setVelocity(bigSat.getVelocity());
+            assignedBigMass += sat.getMass();
+        }
+    }
+
+    //Assign the rest with respect to the already assigned debris-mass for the big satellite
+    //first if: the mass of the bigSat is normed to the actual produced mass of the simulation
+    for (auto &sat : _output) {
```
Comment (gomezzz) [inline src/breakupModel/simulation/Collision.cpp:82]: Is the debris sorted in some way? E.g. by characteristic length? Because then, e.g., this could severely bias the directional outcomes with all small debris flying in one and rest in the other direction if I understand correctly?

File: src/breakupModel/model/Satellite.h [hunk 3]
```diff
@@ -279,6 +294,33 @@ class Satellite {
...
+     * Sets the ejection velocity of this Satellite (debris-fragment)
+     * and adds in on top of the base velocity.
+     * @note This does modifies the state, but the the ejection velocity is property of the breakup and not directly
+     * linked to the Satellite like it is the "whole" velocity. The _orbitalElementsCache is therefore not invalidated.
+     * @param ejectionVelocity - cartesian vector
+     */
+    void addEjectionVelocity(const std::array<double, 3> &ejectionVelocity) {
+        using util::operator+;
+        _ejectionVelocity = ejectionVelocity;
+        _velocity = _velocity + _ejectionVelocity;
```
Comment (gomezzz) [inline src/breakupModel/model/Satellite.h:321]: This seems a little dangerous. What happens if for some reason _velocity was not initialized?

Comment (gomezzz) [reply src/breakupModel/model/Satellite.h:321]: Just wondering if it wasn't better if _velocity and _ejectionVelocity get initiliazed in the same function to avoid any possible scenarios or that happening in the wrong order etc.?

File: src/breakupModel/simulation/Explosion.cpp [hunk 4]
```diff
@@ -15,17 +15,34 @@ void Explosion::generateFragments() {
...
+    double resultMass = 0;
+    auto satIt = _output.begin();
+    for (;satIt != _output.end() && resultMass < inputMass; ++satIt) {
+        satIt->setName(debrisNamePtr);
+        satIt->setVelocity(parent.getVelocity());
+        resultMass += satIt->getMass();
+    }
+
+    //Remove potential "too-much" mass
+    _output.erase(satIt, _output.end());
```
Comment (gomezzz) [inline src/breakupModel/simulation/Explosion.cpp:42]: As above

**Review by gomezzz — CHANGES_REQUESTED** [review]

File: src/breakupModel/simulation/Collision.cpp (hunk 1 above)
Comment (schuhmaj) [reply src/breakupModel/simulation/Collision.cpp:84]: Indeed, fixed

File: src/breakupModel/simulation/Collision.cpp (hunk 2 above)
Comment (schuhmaj) [reply src/breakupModel/simulation/Collision.cpp:82]: Luckily, it's not sorted :)

Nevertheless, I add this in doc to draw attention to the fact that the _output does not have to be sorted when this method is called

File: src/breakupModel/simulation/Collision.cpp [hunk 5]
```diff
@@ -39,17 +39,59 @@ void Collision::generateFragments() {
...
+    //First specify the total mass
+    double inputMass = bigSat.getMass() + smallSat.getMass();
+    double resultMass = 0;
+    auto satIt = _output.begin();
+    for (; satIt != _output.end() && resultMass < inputMass; ++satIt) {
+        resultMass += satIt->getMass();
+    }
+    //Erase potential "too-much" mass
+    resultMass = resultMass > inputMass ? resultMass - (satIt - 1)->getMass() : resultMass;
+    _output.erase(satIt, _output.end());
```
[the remark this answers is not in the document]
Comment (schuhmaj) [reply src/breakupModel/simulation/Collision.cpp:68]: This is an issue with the Method. The process of calculating the debris fragments is not mass conserving.

The python implementation therefore makes sure that the produced mass does not exceed the input mass.
compare line 248ff. (https://github.com/richardklima/Space_debris_removal_model/blob/master/breakup.py#L248)
```python
  idx = np.argmin(np.cumsum(m) < M)
  if idx:
      fragments = fragments[:idx]
```

Until now the simulation always produced less mass which is logic given the fact that we only calculate debris of a specific size and larger. So, this line is more like a final insurance just in case.

File: src/breakupModel/model/Satellite.h (hunk 3 above)
Comment (schuhmaj) [reply src/breakupModel/model/Satellite.h:321]: At the moment, both of them are standardise zero initialized, but i agree that the current method is not that "optimal".

Nevertheless, I would leave it as it is for the moment because those things will undergo a rework with the Data Oriented Approach.

File: src/breakupModel/simulation/Collision.cpp (hunk 5 above)
[the remark this answers is not in the document]
Comment (schuhmaj) [reply src/breakupModel/simulation/Collision.cpp:68]: Hmm, but the question remains if it is required at all. I think we actually should never exceed the input mass.

Life question: Final insurance required or not?

So it might be better to just print a waringing then and let the user decide instead of deleting fragments

[the remark this answers is not in the document]
Comment (schuhmaj) [reply src/breakupModel/simulation/Collision.cpp:68]: Hmm, but the question remains if it is required at all. I think we actually should never exceed the input mass.

Life question: Final insurance required or not?

So it might be better to just print a warning then and let the user decide instead of deleting fragments

File: src/breakupModel/model/Satellite.h (hunk 3 above)
Comment (schuhmaj) [reply src/breakupModel/model/Satellite.h:321]: Just got the idea for the Data Oriented Approach:
I will remove the ejection velocity attribute of Satellite because it's just a property of a breakup. It makes no sense to waste memory for "ejection velocity" for input satellites.

The "Satellite**s**" class on the other hand will contain a possibility to get the ejection velocity because this structure will be used for the output

File: src/breakupModel/simulation/Explosion.cpp (hunk 4 above)
Comment (schuhmaj) [reply src/breakupModel/simulation/Explosion.cpp:42]: As above :)

File: src/breakupModel/simulation/Collision.cpp (hunk 5 above)
[the remark this answers is not in the document]
Comment (schuhmaj) [reply src/breakupModel/simulation/Collision.cpp:68]: So, I've changed the behaviour:
The simulation produces a warning if the output contains more mass than the input.
The idea is that the user can than still remove "too much" mass if it is wished or not.

[the remark this answers is not in the document]
Comment (schuhmaj) [reply src/breakupModel/simulation/Collision.cpp]: Ok, so final iteration:

- The potential reduction of fragments now takes place in the A/M function (because why calculate further A/M values if the mass budget is already consumed, only to throw them away some steps later? Not good)
- I've added a warning which is printed in case of an mass budget exceeding, which surprisingly does happend if one execute the same scenario multiple times

**Comment by schuhmaj** [comment]
In order to prevent huge merge conflicts from happening, I will merge this now into master to begin with the Data Oriented Approach which will rework the files edited in this PR once again.
I will add the "mass conservation" topic to the TO-DISCUSS-POINTS of the Thursday meeting.
